export const FETCHING = '@@discover/FETCHING'
export const FETCHED = '@@discover/FETCHED'
export const RESET = '@@discover/RESET'
export const TOGGLE_DOCK = '@@discover/TOGGLE_DOCK'
export const DISMISS_DOCK = '@@discover/DISMISS_DOCK'
