export const FETCHING = '@@search/FETCHING'
export const FETCHED = '@@search/FETCHED'
export const TOGGLE = '@@search/TOGGLE'
export const DISMISS = '@@search/DISMISS'
export const EMPTY = '@@search/EMPTY'
export const FILTER = '@@search/FILTER'
